### ISSUE TITLE
GA16 alignment issue

### ISSUE THREAD

**Issue by jfbratt** [mapping-elections/site#56] opened 2018-07-24 19:46 UTC
Because the top most geography was removed ("gas_nca") it shifts the state up and slightly beyond the top border of the viewable area.

**Comment by lmullen** [comment] 2018-07-24 19:50
I agree that's a problem, but I don't think that is the cause. We filter the geographies before mapping, so the leaflet centering happens with the geography already removed. Rather I think this is an example of the general problem of sizing, zooming, and centering that we've had since moving to the new version of leaflet. Think I've got this nearly worked out, and this will be a good test case.

**Comment by lmullen** [comment] 2018-11-02 18:43
There is no issue with the state going beyond the top border, at least not any more.

The state does appear to be uncentered because it's an odd shape with the territory in the southwest and because of the short lines of text, but it is clearly centered in the map area.

**Closed as completed by lmullen** 2018-11-02 18:43 UTC
